spring:
  datasource:
    username: root
    password: 123456
    #?serverTimezone=UTC解决时区的报错
    url: jdbc:mysql://localhost:3306/mysql?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver


  mail:
    # 配置 SMTP 服务器地址
    host: smtp.qq.com
    # 发送者邮箱
    username: 1360311705@qq.com
    # 配置密码，注意不是真正的密码，而是刚刚申请到的授权码
    password: gjlteofyfevqhgbi
    # 端口号465或587
    port: 587
    # 默认的邮件编码为UTF-8
    default-encoding: UTF-8
    # 配置SSL 加密工厂
    properties:

      mail:

        smtp:

          socketFactoryClass: javax.net.ssl.SSLSocketFactory

          auth: true
        #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true

mybatis:

  type-aliases-package: com.example.msp.pojo

  mapper-locations: classpath:mapper/*.xml

